project:
  type: website

website:
  title: panukatan
  site-url: https://panukatan.io
  navbar:
    title: panukatan
    background: info
    logo: images/panukatan.png
    logo-alt: panukatan logo
    tools:
      - icon: github
        href: https://github.com/panukatan
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        href: docs/projects/index.qmd
        # menu:
        #   - href: projects/software.qmd
        #   - href: projects/workflow.qmd
      - text: About
        menu:
          - href: docs/about/team.qmd
          - href: docs/about/contact.qmd
  sidebar:
    - id: projects
      collapse-level: 1
      contents:
        - section: Projects
          href: docs/projects/index.qmd
          contents:
            - section: R Packages
              contents:
                - text: bagyo
                  href: docs/software/bagyo.qmd
                - text: covidphtext
                  href: docs/software/covidphtext.qmd
                - text: lindol
                  href: docs/software/lindol.qmd
                - text: openbangsamoro
                  href: docs/software/openbangsamoro.qmd
                - text: openmarawi
                  href: docs/software/openmarawi.qmd
            - section: Workflows
              contents:
                - text: paglaom
                  href: docs/workflow/paglaom.qmd
    - id: team

  page-footer:
    center: "Copyright 2024, Ernest Guevarra"
    background: light
    border: false
  reader-mode: true
  repo-url: https://github.com/panukatan/panukatan.github.io
  repo-actions: [edit, issue]
  issue-url: https://github.com/panukatan/panukatan.github.io/issues
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: ""
    anonymize-ip: true

format:
  html:
    theme: cosmo
    css: styles.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem
    toc: true
