---
title: "Welcome to panukatan"
---

**panukatan** is an open-source project that aims to design and develop tools and systems to manage, analyse, and report various publicly-available data relevant to the Philippines for research and education purposes. It also hopes to contribute data and content usable for teaching science, technology, engineering, and mathematics (STEM) topics and for capacity-building on data literacy and data management. The term **panukatan** is a Filipino word that loosely translates to "metrics" or "standards", which reflects the project's overarching goal of providing standardised data, robust data tools, systems, and methods that support research and education in the Philippine context.

**panukatan** is intended for research scientists working on topics related to the Philippines who require a robust set of tools and a system for managing and analysing data. It is also intended for various students and learners interested in topics related to the Philippines who need datasets and tools they can use for their studies and for learning fields related to data. Its open-source nature makes it accessible to a wide audience, allowing for continuous improvement and adaptation to various use cases.

The **panukatan** project exemplifies a collaborative effort to create a robust yet flexible toolkit for data-driven decision-making, tailored to the needs of research and learning communities in the Philippines.
